# Generated by Django 5.2.7 on 2025-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topupproduct_alter_akungaming_gambar_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='midtrans_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
