# Generated by Django 5.2.7 on 2025-10-17 18:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pembelian_midtrans_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='ulasan',
            field=models.TextField(blank=True),
        ),
    ]
