# Generated by Django 5.2.7 on 2025-10-18 10:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_akungaming_favorited_by_pembelian_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('diskon_persen', models.PositiveSmallIntegerField(help_text='Diskon dalam persentase (misal: 10 untuk 10%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('digunakan_oleh', models.ManyToManyField(blank=True, related_name='kupon_digunakan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
