# Generated by Django 5.2.7 on 2025-10-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='harga_asli',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga sebelum diskon', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='kupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembelian', to='api.kupon'),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='harga_total',
            field=models.DecimalField(decimal_places=2, help_text='Harga final setelah diskon', max_digits=10),
        ),
    ]
