# Generated by Django 5.2.7 on 2025-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pembelian_harga_asli_pembelian_kupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akungaming',
            name='akun_email',
            field=models.CharField(blank=True, help_text='Email/Username akun game (akan dienkripsi)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='akungaming',
            name='akun_password',
            field=models.CharField(blank=True, help_text='Password akun game (akan dienkripsi)', max_length=255, null=True),
        ),
    ]
