# Generated by Django 5.2.7 on 2025-10-18 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_akungaming_akun_email_akungaming_akun_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_user_id', models.CharField(max_length=100)),
                ('game_zone_id', models.CharField(blank=True, max_length=50, null=True)),
                ('harga_pembelian', models.DecimalField(decimal_places=2, help_text='Harga final setelah diskon', max_digits=10)),
                ('harga_asli', models.DecimalField(blank=True, decimal_places=2, help_text='Harga sebelum diskon', max_digits=10, null=True)),
                ('kode_transaksi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('midtrans_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('kupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_pembelian', to='api.kupon')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topupproduct')),
            ],
        ),
    ]
