# Generated by Django 5.2.7 on 2025-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_topuppembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuppembelian',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='topup_images/'),
        ),
    ]
