# Generated by Django 5.2.7 on 2025-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_topuppembelian_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuppembelian',
            name='gambar',
        ),
        migrations.AddField(
            model_name='topupproduct',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='topup_images/'),
        ),
        migrations.AlterField(
            model_name='akungaming',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='account_images/'),
        ),
        migrations.AlterField(
            model_name='akungaming',
            name='game',
            field=models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Lainnya', 'Lainnya')], max_length=50),
        ),
    ]
