# Generated by Django 5.2.7 on 2025-10-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_topuppembelian_gambar_topupproduct_gambar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunGamingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='account_gallery/')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.akungaming')),
            ],
        ),
    ]
