# Generated by Django 5.2.7 on 2025-10-20 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_akungamingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='topup',
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='harga_asli',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='harga_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='kode_transaksi',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='topuppembelian',
            name='harga_asli',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='topuppembelian',
            name='harga_pembelian',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='topuppembelian',
            name='kode_transaksi',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='topupproduct',
            name='game',
            field=models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Lainnya', 'Lainnya')], max_length=50),
        ),
    ]
