# Generated by Django 5.2.7 on 2025-10-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_akungaming_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupproduct',
            name='game',
            field=models.CharField(choices=[('Mobile Legends', 'Mobile Legends'), ('PUBG Mobile', 'PUBG Mobile'), ('Black Desert Mobile', 'Black Desert Mobile'), ('HAIKYU!!', 'HAIKYU!!'), ('Lainnya', 'Lainnya')], max_length=50),
        ),
    ]
