# Generated by Django 5.2.7 on 2025-11-10 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_topupproduct_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="akungaming",
            name="stock",
            field=models.PositiveIntegerField(
                default=1, help_text="Jumlah stok akun yang tersedia"
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="crypto_address",
            field=models.CharField(
                blank=True,
                help_text="Wallet address untuk crypto payment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="crypto_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Jumlah crypto yang harus dibayar",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="crypto_confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="Waktu konfirmasi pembayaran crypto", null=True
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="crypto_currency",
            field=models.CharField(
                blank=True,
                help_text="Currency code (USDT, ETH, SOL)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="crypto_tx_hash",
            field=models.CharField(
                blank=True,
                help_text="Transaction hash setelah pembayaran",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pembelian",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("MIDTRANS", "Midtrans"),
                    ("CRYPTO_USDT", "USDT"),
                    ("CRYPTO_ETH", "Ethereum (ETH)"),
                    ("CRYPTO_SOL", "Solana (SOL)"),
                ],
                default="MIDTRANS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topupproduct",
            name="stock",
            field=models.PositiveIntegerField(
                default=999,
                help_text="Jumlah stok top-up yang tersedia (999 = unlimited)",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                ("diperbarui_pada", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_transaksi",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("harga_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MIDTRANS", "Midtrans"),
                            ("CRYPTO_USDT", "USDT"),
                            ("CRYPTO_ETH", "Ethereum (ETH)"),
                            ("CRYPTO_SOL", "Solana (SOL)"),
                        ],
                        default="MIDTRANS",
                        max_length=20,
                    ),
                ),
                (
                    "midtrans_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crypto_address",
                    models.CharField(
                        blank=True,
                        help_text="Wallet address untuk crypto payment",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "crypto_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Jumlah crypto yang harus dibayar",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "crypto_currency",
                    models.CharField(
                        blank=True,
                        help_text="Currency code (USDT, ETH, SOL)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "crypto_tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash setelah pembayaran",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "crypto_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Waktu konfirmasi pembayaran crypto",
                        null=True,
                    ),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "kupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.kupon",
                    ),
                ),
                (
                    "pembeli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Order",
                "verbose_name_plural": "Cart Orders",
            },
        ),
        migrations.CreateModel(
            name="CartOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("AKUN", "Akun Gaming"), ("TOPUP", "Top Up")],
                        max_length=10,
                    ),
                ),
                (
                    "game_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "game_zone_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "harga_saat_ditambahkan",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "akun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.akungaming",
                    ),
                ),
                (
                    "cart_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="api.cartorder",
                    ),
                ),
                (
                    "pembelian_akun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_order_item",
                        to="api.pembelian",
                    ),
                ),
                (
                    "pembelian_topup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_order_item",
                        to="api.topuppembelian",
                    ),
                ),
                (
                    "topup_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.topupproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Order Item",
                "verbose_name_plural": "Cart Order Items",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("AKUN", "Akun Gaming"), ("TOPUP", "Top Up")],
                        max_length=10,
                    ),
                ),
                (
                    "game_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Diperlukan untuk top-up",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "game_zone_id",
                    models.CharField(
                        blank=True,
                        help_text="Diperlukan untuk beberapa game",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "harga_saat_ditambahkan",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Harga saat item ditambahkan ke cart",
                        max_digits=10,
                    ),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "akun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.akungaming",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.cart",
                    ),
                ),
                (
                    "topup_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.topupproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("item_type", "AKUN")),
                        fields=("cart", "akun"),
                        name="unique_akun_in_cart",
                    )
                ],
            },
        ),
    ]
